version: 1
groups:
  - annotation: Unfold settings
    options:
      - key: ckanext.unfold.max_file_size
        type: int
        default: 52428800   # 50MB in bytes
        validators: is_positive_integer
        description: Maximum size of archives to process, in bytes. Prevents processing very large files.

      - key: ckanext.unfold.formats
        type: list
        default: rar cbr 7z zip zipx jar tar tar.gz tar.xz tar.bz2 rpm deb ar a lib
        description: Limits which file formats to handle.

      - key: ckanext.unfold.enable_cache
        type: bool
        default: true
        description: Enable caching to improve performance on repeated access.
